// User Action Types
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// Profile Action Types
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL';

// User Requests Action Types
export const USER_REQUESTS_REQUEST = 'USER_REQUESTS_REQUEST';
export const USER_REQUESTS_SUCCESS = 'USER_REQUESTS_SUCCESS';
export const USER_REQUESTS_FAIL = 'USER_REQUESTS_FAIL';
export const USER_REQUEST_CREATE_REQUEST = 'USER_REQUEST_CREATE_REQUEST';
export const USER_REQUEST_CREATE_SUCCESS = 'USER_REQUEST_CREATE_SUCCESS';
export const USER_REQUEST_CREATE_FAIL = 'USER_REQUEST_CREATE_FAIL';
export const USER_REQUEST_UPDATE_REQUEST = 'USER_REQUEST_UPDATE_REQUEST';
export const USER_REQUEST_UPDATE_SUCCESS = 'USER_REQUEST_UPDATE_SUCCESS';
export const USER_REQUEST_UPDATE_FAIL = 'USER_REQUEST_UPDATE_FAIL';

// Cart and Favorites Action Types
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_UPDATE_QUANTITY = 'CART_UPDATE_QUANTITY';
export const CART_CLEAR = 'CART_CLEAR';
export const CART_SET_ITEMS = 'CART_SET_ITEMS';
export const FAVORITES_ADD_ITEM = 'FAVORITES_ADD_ITEM';
export const FAVORITES_REMOVE_ITEM = 'FAVORITES_REMOVE_ITEM';
export const FAVORITES_CLEAR = 'FAVORITES_CLEAR';
export const FAVORITES_SET_ITEMS = 'FAVORITES_SET_ITEMS'; 